# Generated by Django 4.2.6 on 2023-11-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.BinaryField(default=bytes),
        ),
    ]
