# Generated by Django 4.2.6 on 2023-11-07 20:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_response_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
